development:
    adapter: mysql2
    encoding: utf8
    database: mateoscc
    username: mateoscc
    password: mateoscc

production:
    adapter: mysql2
    encoding: utf8
    database: mateoscc
    username: mateoscc
    password: mateoscc
