# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0d9069c775af6e1869abbfb0c3692f5577ee9087642040da1c37b0388ec59a598f9f7f9c633348bfad791b626693b0033b2724859ca15d0ef89cd10d34e3f6b

test:
  secret_key_base: bd10fc7daf793b4a8edac1b33cab2491af7f10dd1115b28e99bb2bfab9e0f93cf4eb6245d2f2e3c8d7457746ab25a2d7348a74ae9991c598ca3a8bd225a01d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
